services:
  - type: web
    name: ssc-techcare
    env: docker
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ssc-postgres
          property: connectionString

databases:
  - name: ssc-postgres
    plan: free